version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}' 
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    environment:
    - 'MONGO_INITDB_ROOT_USERNAME=root'
    - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
  mariadb:
    image: 'mariadb'
    ports:
      - '3308:3306'
    environment:
      - 'MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}' 
