version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}' 
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
