version: '3'
services:
  redis:
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
  postgresql:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRESQL_USERNAME=root'
      - 'POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}'
  mysql:
    image: 'bitnami/mysql'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}' 
  mongodb:
    image: 'bitnami/mongodb'
    ports:
      - '27017:27017'
    environment:
    - 'MONGODB_USERNAME=root'
    - 'MONGODB_PASSWORD=${MONGODB_PASSWORD}'
